apiVersion: v1
kind: Service
metadata:
  name: webapp1
  labels:
    k8s-app: webapp1
spec:
  type: NodePort
  ports:
    - name: "5265"
      protocol: TCP
      port: 5265
      targetPort: 5265
      nodePort: 30015
  selector:
    k8s-app: webapp1
