apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  labels:
    name: otel-collector-config
data:
  config.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc:

    exporters:
      # Export prometheus endpoint
      prometheus:
        endpoint: "0.0.0.0:8889"

      logging:
        logLevel: debug

    processors:
      batch:

    service:
      pipelines:
        traces:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ logging ]
        metrics:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ logging, prometheus ]
        logs:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ logging ]
          